name: 02 Evento issue

on:
  push:
  issues:
    types: 
      - opened
jobs:
  evento-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Evento issue
        run: echo "Se ha abierto un nuevo issue!"