name: 04b - Lint JSON
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Node JS version
        run: node --version
      - name: Install jsonlint
        run: |
          sudo apt-get update
          sudo apt-get install -y jsonlint
      - name: Lint JSON files
        run: jsonlint-php package.json
