name: 05a - Expressions
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Operators demonstration
        run: |
          echo "${{ 'Hello, ' }} ${{ 'world!' }}"
          echo "Comparison: 10 > 5 = ${{ 10 > 5 }}"
          echo "Logical AND: true && false = ${{ true && false }}"
      - name: inspect github context
        id: githubContext
        run: echo "${{ toJson(github) }}"
      - name: Event and Actor
        id: eventActor
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
      - name: Object filters
        id: objectFilters
        run: |
          echo "${{ toJSON(steps) }}"
          echo "${{ join(steps.*.conclusion) }}"